#! /bin/sh
set -e

. /usr/share/debconf/confmodule

# File paths for various configuration files
FILE_PATH_NM_CONFIG=etc/NetworkManager/system-connections
FILE_INTERFACES=/etc/network/interfaces
FILE_NETCFG_CONNECTION_TYPE=/tmp/connection_type

# Flag to determine whether Network Manager is installed.
if in-target dpkg -l network-manager >/dev/null 2>&1; then
	NM_IS_INSTALLED=true
else
	NM_IS_INSTALLED=false
fi

# The type of the connection used during installation
NETCFG_CONNECTION_TYPE=$(cat $FILE_NETCFG_CONNECTION_TYPE | head -n 1)

# netcfg/target_network_config question values
CONFIG_NM="nm_config"
CONFIG_INTERFACES="ifupdown"
CONFIG_LOOPBACK="loopback"

db_get netcfg/target_network_config

# Check for preseeding. If the value of the question is empty then set
# default options.
if [ -z "$RET" ]; then
	if $NM_IS_INSTALLED; then
		db_set netcfg/target_network_config $CONFIG_NM
	else
		if [ "$NETCFG_CONNECTION_TYPE" == "wired" ]; then
			db_set netcfg/target_network_config $CONFIG_INTERFACES
		else # wireless
			db_set netcfg/target_network_config $CONFIG_LOOPBACK
		fi
	fi
fi

# Ask the question regarding how the system should be configured.
db_input medium netcfg/target_network_config || true
db_go || true

db_get netcfg/target_network_config

if [ "$RET" == "$CONFIG_NM" ]; then
	# Copy NM config file. First make sure the directory exists
	mkdir -p /target/$FILE_PATH_NM_CONFIG
	cp /$FILE_PATH_NM_CONFIG/* /target/$FILE_PATH_NM_CONFIG/
	chmod 600 /target/$FILE_PATH_NM_CONFIG/*

	# Rewrite /etc/network/interfaces to contain only loopback
	netcfg write_loopback
fi

if [ "$RET" == "$CONFIG_LOOPBACK" ]; then
	# Rewrite /etc/network/interfaces to contain only loopback
	netcfg write_loopback
fi

# Copy /etc/network/interfaces to target. Note: there's nothing particular to
# be done if the /e/n/i option is chosen, since /e/n/i gets copied in any
# situation.
mkdir -p /target$(dirname $FILE_INTERFACES)
cp $FILE_INTERFACES /target$FILE_INTERFACES

exit 0
